version: 1.0
publish: app
services:
  app:
    image: requarks/wiki:2
    environment:
      DB_TYPE: postgres
      DB_PORT: 5432
      DB_HOST: db
      DB_USER: wiki
      DB_PASS: Password123!
      DB_NAME: wiki
    ports:
      - container: 3000
        public: 80
  db:
    image: postgres:11
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wiki
      POSTGRES_PASSWORD: Password123!
